/**
 * Curated coach directory, seeded from Ron's research CSV (July 2026).
 * Every entry is status "unclaimed": they haven't agreed to be on the
 * platform, so the UI must never expose direct contact routes — contact
 * fields live here only for the future claim flow.
 */

export type Coach = {
  slug: string;
  name: string;
  org: string;
  status: "unclaimed" | "claimed";
  photoUrl: string | null;
  bio: string;
  offerings: string;
  price: string;
  bestFor: string;
  /** Not rendered while unclaimed. */
  contact: string;
  source: string;
  /** Verified Substack newsletter, if the coach runs one. */
  substackUrl?: string;
  /** Defaults to "design" in the seed script when omitted. */
  disciplines?: "design" | "product" | "both";
  /** Role types (lib/taxonomy.ts ROLE_TYPES values) this coach specializes in, if known. */
  specialties?: string[];
  /** Custom headline overriding the auto-derived "<org> · <discipline>" line. */
  title?: string;
};

const STORAGE = "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches";

/** Smart facets, derived from each coach's own copy rather than hand-tagged. */
export function coachLevels(c: Coach): string[] {
  const text = `${c.bestFor} ${c.offerings} ${c.bio}`;
  const out: string[] = [];
  if (/cxo|vp\b|executive|director|cdo/i.test(text)) out.push("Directors & execs");
  if (/manager|management|people-leader|leads\b|head of/i.test(text)) out.push("Managers & leads");
  if (/\bic\b|ics\b|senior designer|craft/i.test(text)) out.push("Senior ICs");
  if (/early|junior|career chang|grads|students|first role|aspiring/i.test(text))
    out.push("Early career");
  return out;
}

export function coachFormats(c: Coach): string[] {
  const text = `${c.offerings} ${c.price}`;
  const out: string[] = [];
  if (/1:1|one-on-one|sessions/i.test(text)) out.push("1:1 coaching");
  if (/cohort|group|mastermind|peer/i.test(text)) out.push("Groups & cohorts");
  if (/masterclass|course|program|workshop|training|curriculum|retreat/i.test(text))
    out.push("Programs & courses");
  return out;
}

export function coachPricing(c: Coach): string {
  return /[$£€]\s?\d|\d+\s?(per|\/)\s?session/i.test(c.price) ? "Published pricing" : "Inquire";
}

export const COACHES: Coach[] = [
  {
    slug: "jesse-james-garrett",
    name: "Jesse James Garrett",
    org: "Intentional Associates",
    status: "unclaimed",
    photoUrl: `${STORAGE}/8c6f5736-0039-4eb0-b52c-66986e2ed8e3.jpg`,
    bio: "Co-founder of Adaptive Path and author of The Elements of User Experience. Shifted to leadership coaching in 2018 and founded his executive coaching practice in 2020. Co-hosts the Finding Our Way podcast with Peter Merholz. Now also works on AI transformation for design orgs.",
    offerings:
      "Private 1:1 executive coaching for design leaders (Head of Design through CxO); Design Leadership Studio, a 6-week small-group coaching program; executive leadership skills development; AI transformation consulting.",
    price: "Not published",
    bestFor: "Director/VP/CDO-level leaders wanting a peer-level thinking partner",
    contact: "https://jessejamesgarrett.com/coaching/ · linkedin.com/in/jessejamesgarrett",
    source: "jessejamesgarrett.com",
  },
  {
    slug: "peter-merholz",
    name: "Peter Merholz",
    org: "Org Design for Design Orgs",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/peter-merholz-64ef19b8-3db6-498e-a8fd-0080ac394e97.jpg",
    bio: "25+ years at the intersection of design, technology and business. Adaptive Path co-founder, co-author of Org Design for Design Orgs, independent consultant focused on the effectiveness of design organizations. Co-hosts Finding Our Way.",
    offerings:
      "Masterclasses (UX/Design Leadership Demystified, career architecture, org design), internal team training, org effectiveness consulting, leadership skills and practices assessment.",
    price: "Masterclasses $209–399 by situation; consulting quoted separately",
    bestFor: "Leaders working on org structure, career ladders, and design's operating model",
    contact: "https://www.petermerholz.com/ · linkedin.com/in/petermerholz",
    source: "petermerholz.com",
  },
  {
    slug: "andy-polaine",
    name: "Andy Polaine",
    org: "Independent",
    status: "unclaimed",
    photoUrl: `${STORAGE}/66414e4e-4840-4d68-8db5-b9c9da1c5a49.jpg`,
    bio: "Design leader, educator, author and host of the Power of Ten podcast. Has coached 160+ designers in leadership and management roles since 2020. Based in Europe, works globally.",
    offerings:
      "1:1 design leadership coaching — mid-career and mid-life inflection points, boundaries, managing up, storytelling and pitching, building design capability, design leadership in the age of AI. Small group coaching by arrangement.",
    price: "Packages of 6 or 12 sessions over 3–12 months; free 30-min fit call",
    bestFor: "Leaders at a career or life inflection point who want depth, not frameworks",
    contact: "https://www.polaine.com/coaching/ · linkedin.com/in/apolaine",
    source: "polaine.com",
  },
  {
    slug: "mia-blume",
    name: "Mia Blume",
    org: "Design Dept.",
    status: "unclaimed",
    photoUrl: `${STORAGE}/5aad33e4-635f-4912-96f3-e51ae230c017.jpg`,
    bio: "Founder of Design Dept., a design leadership coaching and development company started in 2016. Previously held design leadership roles at Pinterest, Square and IDEO.",
    offerings:
      "1:1 coaching matched to an experienced coach on the Design Dept. bench; cohort courses including Design Leadership Fundamentals; team and org development; retreats.",
    price: "Not published; courses priced per cohort",
    bestFor: "Leaders who want a matched coach plus structured curriculum, or team-wide programs",
    contact: "https://www.designdept.co/contact-coaching",
    source: "designdept.co",
    substackUrl: "https://designdept.substack.com",
  },
  {
    slug: "sally-grisedale",
    name: "Sally Grisedale",
    org: "Independent",
    status: "unclaimed",
    photoUrl: `${STORAGE}/8944a2e2-0965-4764-b732-bbffcca54af7.jpg`,
    bio: "Executive coach for user experience and design leaders, working with creative leaders in tech on career direction, brand and influence.",
    offerings:
      "1:1 creative leadership coaching — values and purpose alignment, healthy work habits, personal brand, stakeholder communication, promotion and negotiation, career transitions.",
    price: "Not published; free intro consultation",
    bestFor: "Leaders focused on positioning, negotiation and next-chapter decisions",
    contact: "https://sallygrisedale.com/",
    source: "sallygrisedale.com",
  },
  {
    slug: "nick-finck",
    name: "Nick Finck",
    org: "Craft & Rigor",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/nick-finck-e5ea74b3-2e1e-4bd3-bacc-a4ff28d5b714.jpg",
    bio: "24+ years in UX and product design. Managed design and research teams for 14+ years, led orgs of 30+ people at Fortune 500 companies, ran an agency for five years and taught 250+ design grads.",
    offerings:
      "1:1 coaching and mentoring by career stage — career path and progression, portfolio and resume review, mock interviews, offer and comp negotiation, business acumen and stakeholder buy-in. Team mentoring via Craft & Rigor.",
    price: "$150–200 per session; 4 for $540, 6 for $810; pro-bono slots for underrepresented groups",
    bestFor: "IC to senior IC designers, job seekers, career changers",
    contact: "https://www.nickfinck.com/mentoring.html · linkedin.com/in/nickfinck",
    source: "nickfinck.com",
  },
  {
    slug: "judd-garratt",
    name: "Judd Garratt",
    org: "Guide + Mentor",
    status: "unclaimed",
    photoUrl: `${STORAGE}/43580ad2-795c-4b12-8209-5c873af8daba.png`,
    bio: "Design leader and 10-year Atlassian veteran who now coaches design people-leaders and design craft leaders. Remote-first, works with clients worldwide.",
    offerings:
      "1:1 coaching in design leadership and management — people management as a craft, leading without managing, influencing senior stakeholders, measuring design impact, critique and quality standards. Also team workshops.",
    price: "Not published; free 30-min intro call",
    bestFor: "New and mid-level design managers, and senior ICs leading through craft",
    contact: "https://guideplusmentor.com/design-leadership-coaching",
    source: "guideplusmentor.com",
  },
  {
    slug: "good-maven",
    name: "Good Maven",
    org: "Coaching collective",
    status: "unclaimed",
    photoUrl: `${STORAGE}/f61df05e-8ff3-4839-9dd4-e25cdc17e329.jpg`,
    bio: "Coaching collective founded by Meg, a coach and recruiter who was Meta's first international design recruiter. Bench includes leaders from Meta, Instagram, Apple and Microsoft, coaching in English, French and Spanish.",
    offerings:
      "Full spectrum from career coaching to hard-skill development — leadership craft, product thinking, design feedback, CV and portfolio, interview practice, communication. Mentoring packages for founders and leaders.",
    price: "£350–500 per session; six sessions from £1,950; twelve from £4,000",
    bestFor: "People who want a choice of coaches and published, predictable pricing",
    contact: "https://goodmaven.com/coaching-for-designers",
    source: "goodmaven.com",
    substackUrl: "https://goodmaven.substack.com",
  },
  {
    slug: "julia-whitney",
    name: "Julia Whitney",
    org: "Whitney & Associates · Leading Design",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/julia-whitney-08484767-6450-483b-b826-6ae7210ab700.jpg",
    bio: "Former Executive Creative Director and General Manager of UX & Design at the BBC, now an executive coach working with senior design leaders.",
    offerings:
      "Group coaching for experienced design leaders — five online sessions with a small cohort, participant-led agenda covering influence, conflict, career journey, values and purpose. Also 1:1 executive coaching.",
    price: "Not published; cohort-based via Leading Design",
    bestFor: "Experienced leaders who want peer cohort learning rather than solo coaching",
    contact: "https://leadingdesign.com/coaching/group-coaching-for-experienced-design-leaders",
    source: "leadingdesign.com",
  },
  {
    slug: "design-leadership-guild",
    name: "Design Leadership Guild",
    org: "Designlab",
    status: "unclaimed",
    photoUrl: null,
    bio: "Curated mastermind program for design leaders at Director, VP and CxO level, combining peer groups with professional leadership coaches.",
    offerings:
      "3-month programs with twice-monthly facilitated mastermind sessions in groups of 6–10 peers, a guest speaker series, and a 24/7 virtual community.",
    price: "Not published; program-based",
    bestFor: "Senior leaders wanting network plus coaching, roughly 90 min every two weeks",
    contact: "https://designlab.com/design-leadership-guild",
    source: "designlab.com",
  },
  {
    slug: "kat-take",
    name: "Kat Take",
    org: "Independent",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/kat-take-a6ba0017-f092-4c10-9c4f-833b128742de.jpg",
    bio: "Design leader in tech with 15+ years of experience and 100+ interviews conducted at Amazon. Coaches working professionals and mentors design students, with a focus on women of color in design.",
    offerings:
      "1:1 coaching for career transitions, senior-role targeting and breaking into top tech — mock whiteboard and portfolio interviews, self-advocacy and promotion strategy. Structured five-session program plus 60-minute deep dives.",
    price: "Session and multi-session packages; not published",
    bestFor: "Designers interviewing at big tech, or pushing for promotion",
    contact: "https://www.kattake.com/coach",
    source: "kattake.com",
  },
  {
    slug: "mike-dekker",
    name: "Mike Dekker",
    org: "Independent",
    status: "unclaimed",
    photoUrl: null,
    bio: "UX/UI and product design career coach who deliberately positions outside the big-tech and agency-prestige track, emphasizing real work, impact and creative autonomy.",
    offerings:
      "Fully tailored 1:1 sessions on portfolio building, landing a first role, stakeholder management, using design to solve business problems, communicating value and pricing, and leveraging AI in design work.",
    price: "Not published",
    bestFor: "Independent designers, freelancers and people building a practice outside big tech",
    contact: "https://www.mikedekker.com/service-career-coaching",
    source: "mikedekker.com",
  },
  {
    slug: "alexis-specter",
    name: "Alexis",
    org: "Specter",
    status: "unclaimed",
    photoUrl: null,
    bio: "Product designer running a coaching practice built around a tailored curriculum for aspiring and early-career product designers.",
    offerings:
      "Design career coaching with a custom curriculum, long-term portfolio projects, feedback cycles, and help defining what kind of designer you want to be — from foundational craft to inclusive design and basic coding.",
    price: "Not published; described by clients as unusually affordable",
    bestFor: "Career changers and juniors, not senior leaders",
    contact: "https://www.specter.coach/",
    source: "specter.coach",
  },
  // ---- Added September 2026, from a design + product leadership coach
  // roundup (incl. The CPO Club's 2026 list). See supabase/migrations for
  // provenance notes; "Not published" below covers sources that had no
  // rate or an unverified one.
  {
    slug: "andy-budd",
    name: "Andy Budd",
    org: "Clearleft (sold) · Seedcamp",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/andy-budd-fc742bc4-114e-410c-9e65-cf213e5c2df4.jpg",
    bio: "Founded and sold Clearleft, the UK's leading UX consultancy. Now a venture partner at Seedcamp and startup advisor, coaching design leaders and founders. Started the Design Leadership Slack community for Heads, Directors and VPs of Design.",
    offerings:
      "1:1 coaching — typically six 1-hour sessions every two weeks with light async support between. Separate advising track for founders, plus Leadership Atelier workshops.",
    price: "Not published; send role context for a fit check",
    bestFor: "Design leaders who need commercial credibility, executive presence, and a clearer story for business stakeholders",
    contact: "https://www.andybudd.com/coaching",
    source: "andybudd.com",
  },
  {
    slug: "ryan-rumsey",
    name: "Ryan Rumsey",
    org: "Second Wave Dive · CDO School",
    status: "unclaimed",
    photoUrl: null,
    bio: "20+ years in design and executive roles at Apple, Electronic Arts, USAA, Nestlé and Comcast. Author of Business Thinking for Designers and Play Up Your Impact. CEO of Second Wave Dive and founder of Chief Design Officer School.",
    offerings:
      "1:1 coaching, CDO School training on business and strategy skills, and Second Wave Dive consulting on a subscription model.",
    price: "Not published; Business Thinking for Designers is a free download",
    bestFor: "Design leaders who need to speak the language of the business and win influence with non-design executives",
    contact: "https://www.secondwavedive.com/",
    source: "secondwavedive.com",
  },
  {
    slug: "maria-giudice",
    name: "Maria Giudice",
    org: "Independent",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/maria-giudice-19413675-36eb-4463-b3e5-6b18dfc23b48.jpg",
    bio: "Founded Hot Studio, acquired by Facebook in 2013, then led global design teams at Facebook and Autodesk. Co-author of Rise of the DEO and Changemakers.",
    offerings: "1:1 executive coaching, group coaching, and team-building workshops.",
    price: "Not published",
    bestFor: "Design executives taking on broader business or change-leadership scope, with a personal, whole-self coaching style",
    contact: "https://hotstudio.com",
    source: "hotstudio.com",
  },
  {
    slug: "doug-powell",
    name: "Doug Powell",
    org: "Independent",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/doug-powell-b78bbaad-131d-45f6-843b-fdd8ad14cd4b.jpg",
    bio: "30+ years in design. VP of Design at IBM and Expedia Group, and national president of AIGA (2011–2013). Faculty at Duke's Pratt School of Engineering and WashU's Sam Fox School.",
    offerings: "Leadership training, coaching, and consulting for designers stepping into leadership through executive design leaders.",
    price: "Not published",
    bestFor: "Leaders of large, scaled design orgs or enterprise design programs, and design leaders in a mid-career job search",
    contact: "https://dougpowell.design",
    source: "dougpowell.design",
  },
  {
    slug: "jason-mesut",
    name: "Jason Mesut",
    org: "Resonant",
    status: "unclaimed",
    photoUrl: null,
    bio: "20+ years in UX, design and innovation consulting. Runs Resonant (coaching and consultancy), is a Design Partner at Group of Humans, coaches through Coaching with Chemistry, and co-hosts IxDA London.",
    offerings:
      "Executive coaching, plus 'Shaping' workshops using visual skill frameworks for careers and teams, and strategic consulting.",
    price: "Not published",
    bestFor: "Leaders at a crossroads — job search, IC vs. manager, or reinvention — and teams mapping skills. UK-based.",
    contact: "https://www.linkedin.com/in/jasonmesut",
    source: "linkedin.com/in/jasonmesut",
  },
  {
    slug: "whitney-hess",
    name: "Whitney Hess",
    org: "Independent",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/whitney-hess-850b40e4-2dc1-4c84-9886-9ac29a611001.jpg",
    bio: "10+ years as a UX consultant for the US Holocaust Memorial Museum, Seamless, WNYC and American Express, with a CMU HCI master's. ICF Professional Certified Coach and Certified Integral Coach.",
    offerings: "Executive coaching programs (six-month plans), team coaching, and culture change work.",
    price: "Not published",
    bestFor: "Leaders who want a whole-person, values-driven approach, often at mission-driven organizations",
    contact: "https://whitneyhess.com",
    source: "whitneyhess.com",
  },
  {
    slug: "ken-norton",
    name: "Ken Norton",
    org: "Bring the Donuts",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/ken-norton-6e0a8a30-e4bb-47cc-9a64-976bbc09db24.jpg",
    bio: "14+ years at Google leading Docs, Calendar and Mobile Maps, plus coaching founders at GV. Earlier VP Products at JotSpot and product at Yahoo. ICF PCC and Co-Active certified; full-time coach since 2020.",
    offerings: "1:1 executive coaching built on emotional intelligence, conscious leadership, and 10x thinking.",
    price: "Not published; short intake form, then a call",
    bestFor: "The most senior product leader in a company who feels isolated, stuck, or burnt out — inner-game work more than frameworks",
    contact: "https://www.bringthedonuts.com/coaching/",
    source: "bringthedonuts.com",
    disciplines: "product",
  },
  {
    slug: "nikhyl-singhal",
    name: "Nikhyl Singhal",
    org: "Skip Coach",
    status: "unclaimed",
    photoUrl: null,
    bio: "Three-time founder, CPO at Credit Karma, VP of Product at Meta (Feed, Stories, Groups), and product leader at Google (Photos, Hangouts).",
    offerings:
      "Skip Coach career service — live sessions with 125+ product leaders, curated roles, and a talent network — plus the Skip Community for CPOs.",
    price: "Live sessions listed as free; community pricing not published",
    bestFor: "Senior product leaders working through job changes, promotions, and AI-era reinvention",
    contact: "https://skip.coach",
    source: "skip.coach",
    substackUrl: "https://theskip.substack.com",
    disciplines: "product",
  },
  {
    slug: "petra-wille",
    name: "Petra Wille",
    org: "Independent",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/petra-wille-e00abfb6-5457-49da-a31c-94be675808d5.jpg",
    bio: "Former product leader, independent product leadership coach since 2013. Author of STRONG Product People and creator of the #52questions coaching cards. Co-organizes Mind the Product Engage Hamburg.",
    offerings: "Coaching for product leaders, workshops, and coaching tools.",
    price: "Not published",
    bestFor: "New leaders of PMs who need to hire, coach, and grow their team. Hamburg-based, works globally.",
    contact: "https://www.petra-wille.com/",
    source: "petra-wille.com",
    disciplines: "product",
  },
  {
    slug: "hope-gurion",
    name: "Hope Gurion",
    org: "Fearless Product",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/hope-gurion-6605caba-8338-48c4-b051-69b006791067.jpg",
    bio: "Former CPO and SVP of Product across B2B, B2C, and marketplaces. Has coached 50+ product leaders and 100+ teams at 70+ companies. Featured in Marty Cagan's Transformed; teaches with Product Talk Academy.",
    offerings: "Leader and team coaching on outcome-driven product work and continuous discovery.",
    price: "Not published",
    bestFor: "Leaders moving an org from shipping features to hitting outcomes",
    contact: "https://fearless-product.com/about-me",
    source: "fearless-product.com",
    disciplines: "product",
  },
  {
    slug: "rich-mironov",
    name: "Rich Mironov",
    org: "Mironov Consulting",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/rich-mironov-41b836fb-f304-400c-aeb0-ca788b30033b.jpg",
    bio: "Longtime software executive who has served as interim VP of Product or CPO at many companies. Author and advisor, based near Lisbon.",
    offerings: "Executive coaching, interim product leadership, and org design consulting.",
    price: "Not published",
    bestFor: "Heads of product fixing org structure, executive alignment, or a struggling product function",
    contact: "https://www.mironov.com/",
    source: "mironov.com",
    disciplines: "product",
  },
  {
    slug: "joni-hoadley",
    name: "Joni Hoadley",
    org: "Independent",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/joni-hoadley-f093f17f-8d2f-4322-8ac4-1fefbc32ffd8.jpg",
    bio: "20+ years in product, including more than a decade at Sonos as it grew from 50 to 1,500 employees.",
    offerings: "1:1 leadership coaching, team workshops, PM onboarding, and product operating model resets.",
    price: "Not published; free intro call",
    bestFor: "First-time product leaders with a bigger scope and fewer resources",
    contact: "https://jonihoadley.com/",
    source: "jonihoadley.com",
    disciplines: "product",
  },
  {
    slug: "kate-leto",
    name: "Kate Leto",
    org: "Independent",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/kate-leto-4379004b-452a-4bb4-8000-ab8ec69bb82c.png",
    bio: "25 years across product management, organizational design, and leadership development. Author and speaker, based in the UK and France.",
    offerings: "Executive coaching for senior product and technology leaders.",
    price: "Not published",
    bestFor: "Leaders working on leadership style, team culture, and org design",
    contact: "https://www.kateleto.com/",
    source: "kateleto.com",
    disciplines: "product",
  },
  {
    slug: "gabrielle-bufrem",
    name: "Gabrielle Bufrem",
    org: "Independent",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/gabrielle-bufrem-06a31cd3-9391-4137-8c91-a19cf58b51c0.png",
    bio: "Built products across nine industries on three continents before coaching. New York-based.",
    offerings: "Product leadership coaching and advising.",
    price: "Not published",
    bestFor: "Leaders who want coaching on strategy, discovery, and empowered teams, with an NYC-based coach",
    contact: "https://www.gabriellebufrem.com/",
    source: "gabriellebufrem.com",
    disciplines: "product",
  },
  {
    slug: "melissa-perri",
    name: "Melissa Perri",
    org: "Produx Labs",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/melissa-perri-c8466a17-703b-47f0-8109-57ce2f52ed13.jpg",
    bio: "Author of Escaping the Build Trap and Product Operations. Founder of Produx Labs (Product Institute and CPO Accelerator). Former Harvard Business School lecturer, board member and advisor.",
    offerings:
      "Online schools and cohort programs with mentors (Product Institute through the CPO Accelerator), plus executive and board advisory.",
    price: "Not published",
    bestFor: "VPs aiming for a CPO seat who want a structured curriculum and a peer cohort",
    contact: "https://melissaperri.com/",
    source: "melissaperri.com",
    disciplines: "product",
  },
  {
    slug: "teresa-torres",
    name: "Teresa Torres",
    org: "Product Talk",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/teresa-torres-07d8bbe4-5d46-483f-8537-16fb2935bf07.jpg",
    bio: "Author of Continuous Discovery Habits. Runs Product Talk and Product Talk Academy.",
    offerings: "Courses through Product Talk Academy and team coaching on continuous discovery.",
    price: "Not published",
    bestFor: "Product trios and their leaders adopting a discovery practice — relevant to design leaders as well as PMs",
    contact: "https://www.producttalk.org/",
    source: "producttalk.org",
    disciplines: "both",
  },
  {
    slug: "shreyas-doshi",
    name: "Shreyas Doshi",
    org: "High Leverage Labs",
    status: "unclaimed",
    photoUrl: null,
    bio: "Product leadership roles at Stripe, Twitter, Google and Yahoo. Founder of High Leverage Labs.",
    offerings: "Teaching on product sense, strategy, and leadership; executive coaching listed but availability looks limited.",
    price: "Not published",
    bestFor: "Leaders sharpening judgment, product sense, and strategy",
    contact: "https://shreyasdoshi.com/",
    source: "shreyasdoshi.com",
    disciplines: "product",
  },
  {
    slug: "ant-murphy",
    name: "Ant Murphy",
    org: "Product Pathways",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/ant-murphy-9429e876-1ea7-46a0-9930-5de5ac89ee8c.png",
    bio: "Led product groups in media and fintech, then founded Product Pathways. Based in Sydney.",
    offerings: "Coaching, mentorship, and education through Product Pathways.",
    price: "Not published",
    bestFor: "PMs and new leaders who want practical help on strategy and stakeholders — good for APAC time zones",
    contact: "https://www.antmurphy.me/",
    source: "antmurphy.me",
    disciplines: "product",
  },
  {
    slug: "itamar-gilad",
    name: "Itamar Gilad",
    org: "Independent",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/itamar-gilad-b67bcf2d-d809-4afb-baab-303c29d695e3.png",
    bio: "20+ years in product including senior roles at Google and Microsoft. Created the GIST framework. Based in Barcelona.",
    offerings: "Coaching, workshops, and talks on evidence-guided product development.",
    price: "Not published",
    bestFor: "Orgs moving to evidence-based goals and prioritization",
    contact: "https://itamargilad.com/",
    source: "itamargilad.com",
    disciplines: "product",
  },
  {
    slug: "tim-herbig",
    name: "Tim Herbig",
    org: "Independent",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/tim-herbig-3890d67a-32f1-43c9-8a64-49bc34024e64.jpg",
    bio: "Product management coach, consultant, author, and speaker based in Hamburg.",
    offerings: "Coaching, workshops, and courses on strategy, OKRs, and discovery.",
    price: "Not published",
    bestFor: "Teams trying to connect strategy, OKRs, and discovery work",
    contact: "https://herbig.co/",
    source: "herbig.co",
    disciplines: "product",
  },
  {
    slug: "gibson-biddle",
    name: "Gibson Biddle",
    org: "Independent",
    status: "unclaimed",
    photoUrl: null,
    bio: "VP of Product at Netflix and CPO of Chegg. Now teaches, speaks, advises, and coaches.",
    offerings: "Workshops, teaching, advising, and coaching.",
    price: "Not published",
    bestFor: "Consumer product leaders working on strategy and culture",
    contact: "https://www.gibsonbiddle.com/",
    source: "gibsonbiddle.com",
    disciplines: "product",
  },
  {
    slug: "tami-reiss",
    name: "Tami Reiss",
    org: "The Leader Within",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/tami-reiss-c87c6695-c26d-4aa0-970a-4393a0bea9df.jpg",
    bio: "Former CPO-in-Residence with a background in product strategy and executive leadership. Runs The Leader Within programs.",
    offerings: "Leadership training programs, coaching, and speaking.",
    price: "Not published",
    bestFor: "Leaders working on influence, executive communication, and alignment",
    contact: "https://tamireiss.com/",
    source: "tamireiss.com",
    disciplines: "product",
  },
  {
    slug: "marty-cagan",
    name: "Marty Cagan",
    org: "Silicon Valley Product Group (SVPG)",
    status: "unclaimed",
    photoUrl: "https://ziaylaegutxikckewwnq.supabase.co/storage/v1/object/public/profile-assets/coaches/marty-cagan-795eb1de-5540-4971-b5f7-d92307214cc6.jpg",
    bio: "Founded Silicon Valley Product Group after product leadership roles at HP, Netscape, and eBay. Author of Inspired, Empowered, and Transformed.",
    offerings: "Workshops and coaching for product transformations, often delivered with SVPG partners.",
    price: "Not published",
    bestFor: "Companies moving to a product operating model — less suited to individual career coaching",
    contact: "https://www.svpg.com/team/marty-cagan/",
    source: "svpg.com/team/marty-cagan",
    disciplines: "product",
  },
  {
    slug: "frank-harris",
    name: "Frank Harris",
    org: "Independent",
    status: "unclaimed",
    photoUrl: null,
    bio: "20+ years across engineering, design, and product leadership. Held VP roles at Betterment, Casper, InVision, and Slack; earlier a UX designer at Google and a PM at Etsy pre-IPO. Certified Professional Co-Active Coach (CPCC).",
    offerings:
      "Focused Sprint (6 sessions over 4 months) for senior ICs and new managers. Standard Engagement (13 sessions over 6 months, unlimited async support) for executives and founders. Corporate coaching for teams.",
    price: "Not published; discussed on a complimentary 30-minute intro call",
    bestFor: "Executives and founders navigating reorgs, scaling teams, and high-stakes transitions, plus senior ICs building influence and visibility",
    contact: "https://hirefrank.com/coaching/",
    source: "hirefrank.com",
    substackUrl: "https://www.franktakeaways.com",
    disciplines: "product",
  },
  // ---- Content design and user research specialists, added September 2026.
  {
    slug: "kate-agena",
    name: "Kate Agena",
    org: "Content Design Leaders",
    status: "unclaimed",
    photoUrl: null,
    bio: "Founded Content Design Leaders after leading content design teams at IBM, McAfee, and SAP.",
    offerings:
      "A peer community rather than 1:1 coaching — a 24/7 community app, 3-5 monthly live sessions with recordings, goal-setting and accountability support, and monthly themed leadership activities.",
    price: "$124/month or $1,440/year; limited free guest access",
    bestFor: "Leaders of UX content design practices (management or staff/principal IC track), plus senior ICs growing into leadership",
    contact: "https://www.contentdesignleaders.com/",
    source: "contentdesignleaders.com",
    disciplines: "design",
    specialties: ["content_design"],
  },
  {
    slug: "marie-anne-chaloupecky",
    name: "Marie-Anne Chaloupecky",
    org: "Ways of Words",
    status: "unclaimed",
    photoUrl: null,
    bio: "UX and content design coach blending classic coaching with design-thinking methods suited to Agile settings. Clients include a senior UX writing manager at Qonto and a former content design manager at Zalando.",
    offerings:
      "1:1 coaching on craft, strategy, career progression, and management skills for content designers at any level, junior to principal.",
    price: "€180 for a single session; €1,250 for three; €1,650 for five; €2,800 for ten",
    bestFor: "Content designers at any career level wanting individual coaching",
    contact: "https://waysofwords.com/coaching-mentorship-for-content-designers/",
    source: "waysofwords.com",
    disciplines: "design",
    specialties: ["content_design"],
  },
  {
    slug: "content-design-london",
    name: "Content Design London",
    org: "Content Design London",
    status: "unclaimed",
    photoUrl: null,
    bio: "A UK-based content design consultancy and training organization.",
    offerings: "Leadership coaching for content design practitioners, arranged by email.",
    price: "Not published",
    bestFor: "Content design leaders wanting direct, arranged coaching",
    contact: "mailto:hello@contentdesign.london",
    source: "contentdesign.london",
    disciplines: "design",
    specialties: ["content_design"],
  },
  {
    slug: "ux-content-collective",
    name: "UX Content Collective",
    org: "UX Content Collective",
    status: "unclaimed",
    photoUrl: null,
    bio: "A collective of roughly 20 working content design practitioners from companies including Google, Meta, Intuit, Peloton and PayPal, offering coaching across North America, Europe, APAC and the Middle East.",
    offerings:
      "1:1 sessions with practitioner coaches for career advice, portfolio feedback, and interview prep, plus a live cohort program on running content as a business-impact function.",
    price: "$100–200/hour depending on coach seniority",
    bestFor: "Content designers at any stage — breaking in, leveling up, or moving into leadership",
    contact: "https://uxcontent.com/ux-coaching-mentoring/",
    source: "uxcontent.com",
    disciplines: "design",
    specialties: ["content_design"],
  },
  {
    slug: "nikki-anderson",
    name: "Nikki Anderson",
    org: "The User Research Strategist",
    status: "unclaimed",
    photoUrl: null,
    bio: "12+ years in UX research. Founded User Research Academy in 2019, now The User Research Strategist. Has trained 2,000+ researchers at Bosch, Amazon, HelloFresh, GOV.UK, and Google. Writes a weekly Substack read by 15,000+ subscribers on the craft of research, impact, and AI — in 2024 she said coaching researchers took up most of her time.",
    offerings:
      "1:1 coaching and live workshops (via Maven) focused on moving researchers from tactical execution into strategic partnership.",
    price: "Not published",
    bestFor: "User researchers wanting to move from tactical execution into strategic, business-facing partnership",
    contact: "https://maven.com/user-research-strategist",
    source: "userresearchstrategist.com",
    substackUrl: "https://www.userresearchstrategist.com",
    disciplines: "both",
    specialties: ["user_research"],
  },
  {
    slug: "amy-santee",
    name: "Amy Santee",
    org: "Independent",
    status: "unclaimed",
    photoUrl: null,
    bio: "15 years studying organizations and their impact on individuals, spanning UX research, tech work, and labor activism before moving into coaching. Former senior design researcher at eBay and researcher at State Farm.",
    offerings:
      "Career strategy coaching for experienced professionals navigating role changes, grinding org cultures, or a career path that's run its course — examining systemic and organizational dynamics rather than generic optimization advice.",
    price: "Not published",
    bestFor: "Burned-out or restless professionals with a research/UX background wanting clarity on what's next",
    contact: "https://amysantee.com",
    source: "amysantee.com",
    disciplines: "both",
    specialties: ["user_research"],
  },
  {
    slug: "meltem-naz-kaso",
    name: "Meltem Naz Kaso",
    org: "Career With Mel",
    status: "unclaimed",
    photoUrl: null,
    bio: "Former UX Research Manager and Staff UX Researcher at Glovo (Delivery Hero). Based in Barcelona. Facilitator at Leadership Ateliers.",
    offerings:
      "Career coaching focused on leadership and communication skills, using a Clarity/Alignment/Resilience/Expression framework, plus in-person Leadership Ateliers workshops.",
    price: "Not published; discussed via an 'Explore the fit' intake form",
    bestFor: "Senior researchers stuck on the path to a lead or manager role",
    contact: "https://careerwithmel.com",
    source: "careerwithmel.com",
    disciplines: "both",
    specialties: ["user_research"],
  },
  {
    slug: "mb-collab",
    name: "MB Collab",
    org: "MB Collab",
    status: "unclaimed",
    photoUrl: null,
    bio: "UX research coaching run by Irina Lasselle and Serene Mireles, who've built and led design and research teams across startups and enterprises.",
    offerings:
      "Coaching packages covering landing a first research role, advancing into senior or strategic research positions, and building stakeholder buy-in for research.",
    price: "$400 for one session with a week of email support; $1,000 for three sessions over a quarter; $1,300 for a four-week intensive. Free 30-minute discovery call.",
    bestFor: "New and mid-career UX researchers, and professionals transitioning into research from design or development",
    contact: "https://mbcollab.com/coaching/ux-research-coaching",
    source: "mbcollab.com",
    disciplines: "both",
    specialties: ["user_research"],
  },
];
